spring.data.mongodb.uri=mongodb+srv://usrinivasulu2005_db_user:tRaucqoL5IB0V7j7@tastycluster.yobfruu.mongodb.net/
spring.data.mongodb.database=tastyDB
server.port=${PORT:8081}

# Faster MongoDB connection
spring.data.mongodb.auto-index-creation=true

server.error.include-stacktrace=always
server.error.include-message=always
