spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/tastyDB}
spring.data.mongodb.database=tastyDB
server.port=${PORT:8081}

# Faster MongoDB connection
spring.data.mongodb.auto-index-creation=true

server.error.include-stacktrace=always
server.error.include-message=always
